### PR TITLE
Backup and copy the images directory over a tmpfs directory

### PR DESCRIPTION
**Pull request by rhatdan**
The idea here is if a user chooses to use a tmpfs over a directory, then we
want the content of the images directory to be preserved.  The first use
case I would like to use for this would be /run.  But if the --tmpfs patch or
similar got merged, I think you would need something like this patch.

Docker-DCO-1.1-Signed-off-by: Dan Walsh <dwalsh@redhat.com> (github: rhatdan)

### CODE REVIEW

**Comment by rhatdan** [comment]
Playing around with this, I have seen problems with potential symlinks. For example I tried this with a tmpfs on /etc, and it blew up.  We might want to change it to reporting a warning rather then an error.

**Comment by mrunalp** [comment]
@rhatdan will have to vendor logrus package (from the build failures).

**Comment by crosbymichael** [comment]
We cannot import the archive package in libcontainer and cannot copy files in libcontainer.

Sorry but we will not copy file like this in libcontainer.

**Comment by rhatdan** [comment]
Any suggestion on how we could do this then?

**Pull request closed without merging**
