### PR TITLE
Add checkpoint/restore functionality to nsinit and libcontainer

### PR DESCRIPTION
**Pull request by SaiedKazemi**
New code was added to nsinit and libcontainer to use the criu(8) utility
to checkpoint and restore a container.

While there are no hard-coded assumptions about Docker, the new C/R
functionality has only been tested with Docker containers.

The nsinit command line usage for checkpoint and restore is consistent
with the rest of nsinit commands.  However, for easier C/R usage, the
user can specify the container ID on the command line.  The best way
to get started is to run "nsinit checkpoint --help" and look at the
"EXAMPLE:" section.

Signed-off-by: Saied Kazemi <saied@google.com>

### CODE REVIEW

**Comment by bridiver** [comment]
what is the current status of this?

**Comment by SaiedKazemi** [comment]
@bridiver 
C/R is already integrated into the criu branch of the new libcontainer (https://github.com/docker/libcontainer/pull/479), waiting to be merged into the master branch.

**Comment by bridiver** [comment]
Great! We have a use case where we want to repeatedly restore a container to a "pristine" state during a series of tests.

**Comment by crosbymichael** [comment]
Closing this as we merged the criu branch into master

**Pull request closed without merging**
