### PR TITLE
cgroups: add support for net_cls

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by vmarmol** [comment]
You'll need to rebase btw

**Comment by vmarmol** [comment]
Looks good otherwise

**Comment by crosbymichael** [comment]
I also think you have to register the net handlers with the fs code here:
https://github.com/docker/libcontainer/blob/master/cgroups/fs/apply_raw.go#L17

**Comment by Mashimiao** [comment]
@vmarmol , @crosbymichael 
fixed and rebased

**Comment by dqminh** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
