### PR TITLE
nsenter: noop reference to C constructor

### PR DESCRIPTION
**Pull request by vbatts**
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65134
Workaround suggested by iant

Reported here https://github.com/docker/docker/issues/9207#issuecomment-75354189

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, although the built appears to be failing.

**Comment by vbatts** [comment]
Interesting. Off hand it doesn't seem related.

**Comment by avagin** [comment]
LGTM.

I think the test fails, because we use Cmd.Start(), but don't used Cmd.Wait(), so we don't wait until all cmd.goroutine are completed.

Cc: @crosbymichael

**Comment by mrunalp** [comment]
@avagin Hmm, yeah, will have to call cmd.Wait instead of process.Wait. This will mean modifying the API to be able to call Wait on the cmd.

**Comment by mrunalp** [comment]
Another option might be to use os.StartProcess.

**Comment by crosbymichael** [comment]
I testing locally and it looks like that test races for some of the reasons above.  We can merge this one and look into the wait issues.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
