### PR TITLE
Adds an integration test for checking process env.

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by LK4D4** [comment]
@mrunalp Nice! Also idea is always to have `$HOME` set, maybe makes sense to test it too.

**Comment by mrunalp** [comment]
@LK4D4 Sure, will add that.

**Comment by mrunalp** [comment]
@LK4D4 @avagin updated, thanks!

**Comment by crosbymichael** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
