### PR TITLE
Merge API Branch into Master

### PR DESCRIPTION
**Pull request by crosbymichael**

### CODE REVIEW

**Comment by vmarmol** [comment]
GitHub seems angry that it can't auto-merge. Does that mean we need a rebase or are we gonna force push?

**Comment by vmarmol** [comment]
But generally: :+1: :)

**Comment by crosbymichael** [comment]
I made github happy now

**Comment by vmarmol** [comment]
LGTM, unless anyone has any reservations I think we're ready to merge :)

Huuuge shout out to @avagin who did most of the work on getting us here! @mrunalp and @crosbymichael getting us back in shape so this has feature-parity with HEAD

**Comment by crosbymichael** [comment]
Yes, thanks to everyone.  I would say that this will be iterated on in master then when we feel comfortable we can tag it at v2 just incase we need to many any additional api or config changes.

**Comment by vmarmol** [comment]
Merging...

**Comment by mrunalp** [comment]
LGTM awesome stuff :+1:

**Comment by LK4D4** [comment]
Haha, late to party. Comment for `container.Start` is pretty misleading :)

**Pull request merged**
