### PR TITLE
Initial integration of libct into libcontainer

### PR DESCRIPTION
**Pull request by avagin**
This patch adds new factory and container classes to create and manage
containers via LibCT.

This implementation is incomplete, but I think it's enough to start an
integration process.

LibCT is a library for creating and managing containers. It has ability
to add different backends. Currently it has a native backend and a backend for
OpenVZ and PCS.

### CODE REVIEW

**Comment by LK4D4** [comment]
@avagin Any ideas about size of binary with libct? Is it will be bigger or smaller?

**Comment by LK4D4** [comment]
@avagin Also I think it makes sense to create build tag for integration time. So we can prepare integration without affecting docker dependencies for example.

**Comment by mrunalp** [comment]
I agree with @LK4D4 that it might be better use build tags for this right now.

**Comment by mrunalp** [comment]
I am trying to build this directly on Fedora and had to disable CONFIG_APPARMOR in Makefile.config. It would be nice if we can automate that.

**Comment by mrunalp** [comment]
make all  is failing for me with --
```
....
cd vendor/src/github.com/avagin/libct && \
make
make[1]: Entering directory '/go/src/github.com/docker/libcontainer/vendor/src/github.com/avagin/libct'
make[2]: *** No rule to make target '/usr/include/sys/cdefs.h', needed by 'src/net.o'.  Stop.
Makefile:134: recipe for target 'src/libct.a' failed
make[1]: Leaving directory '/go/src/github.com/docker/libcontainer/vendor/src/github.com/avagin/libct'
make[1]: *** [src/libct.a] Error 2
Makefile:27: recipe for target 'libct' failed
make: *** [libct] Error 2
INFO[0064] The command [/bin/sh -c make direct-install] returned a non-zero code: 2 
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by avagin** [comment]
@mrunalp Thank you for the feedback. I have updated libct and now it can determine existence of libselinux and libapparmor automatically.

And you need to install glibc-headers to fix the second issue.
[avagin@localhost ~]$ rpm -qf /usr/include/sys/cdefs.h 
glibc-headers-2.20-7.fc21.x86_64

**Comment by avagin** [comment]
@LK4D4 I have add the libct build tag, so libcontainer is built without support of libct by default.

Looks like libct can't significantly affect a binary size.
```
$ go build --tags libct -o nsinit .
$ ls -l nsinit 
-rwxr-xr-x 1 root root 7497717 Mar 11 15:15 nsinit
$ go build -o nsinit .
$ ls -l nsinit 
-rwxr-xr-x 1 root root 7427230 Mar 11 15:15 nsinit
```

**Comment by LK4D4** [comment]
@avagin Nice, thank you!

**Comment by mrunalp** [comment]
@avagin Thanks for the changes. I will try them out.

**Comment by LK4D4** [comment]
@avagin I don't like only one thing about this patch - compile time :) Is it possible to copy `libnetlink` from `ipoute2` instead of using `libnl`? Or it's not worth it?

**Comment by mrunalp** [comment]
Well one option might be to not compile from source and use the library from the distribution, but that may not be feasible if there is a hard dependency on a minimum version of libnl that isn't available everywhere.

**Comment by avagin** [comment]
@LK4D4 libnetlink from iproute isn't enough... it's too small, the most part of logic in the ip util. libct and libnl don't need to compile each time, only after updating them.

**Comment by avagin** [comment]
@mrunalp When I started to use libnl in libct, distributives doesn't provide a required version of libnl.  The minimum required version is 3.2.24. Now I see that f21 has a recent version and we can work with it.
$ rpm -q libnl3
libnl3-3.2.25-5.fc21.x86_64

I don't know which version is used in the last Ubuntu. I will try to determine automatically when we need to compile libnl. Thanks.

**Comment by mrunalp** [comment]
@avagin +1. That is a good idea.

**Comment by avagin** [comment]
@mrunalp Fedora doesn't compile static libraries...
http://pkgs.fedoraproject.org/cgit/libnl3.git/tree/libnl3.spec?h=f16#n55

**Comment by mrunalp** [comment]
@avagin Hmm, too bad. I will ping the maintainer and see if static version could be enabled.

**Comment by avagin** [comment]
What does this mean?
```
$curl -sSL https://raw.githubusercontent.com/docker/docker/master/project/dind
Not Found
```

**Comment by dqminh** [comment]
@avagin oops, i think that has to be changed to https://raw.githubusercontent.com/docker/docker/master/hack/dind

That script was moved a few days ago https://github.com/docker/docker/pull/11373

**Comment by mrunalp** [comment]
@avagin I talked with the Fedora libnl maintainers and there is a guideline not to compile static unless absolutely required http://fedoraproject.org/wiki/Packaging:Guidelines#Packaging_Static_Libraries

Could we dynamically link to libnl?

**Comment by LK4D4** [comment]
@avagin Also, I have proposal about Dockerfile. Can we first copy vendored libct and build it and only then copy whole libcontainer? That'll allow to have cached built C-libs and not rebuild them every time when you change code.

**Comment by avagin** [comment]
@LK4D4 It's really good point. Thanks a lot.

@mrunalp Now libnl is linked dinamically if libcontainer is built locally. And it is linked statically if libcontainer is built in a docker container, because in this case we may want to take nsinit and execute it outside of the container.

I think I have fixed all comments. Could you look at this once again? Thanks.

**Comment by mrunalp** [comment]
@avagin Thanks for making the changes. I will try it again today.

**Comment by mrunalp** [comment]
@avagin I think you need to rebase. We took out baseMounts to move all mounts to the config.

**Comment by avagin** [comment]
@mrunalp done

**Comment by mrunalp** [comment]
@avagin Thanks. I can build it on Fedora 21 directly now.

**Comment by avagin** [comment]
Today I noticed that tests with libct are working faster https://asciinema.org/a/18232

**Comment by LK4D4** [comment]
@avagin Makes sense to write simple go benchmarks for running/destroying containers with different configurations. And then compare libct/libcontainer results with benchcmp. It can be additional argument for moving to libct sooner.

**Comment by mrunalp** [comment]
@avagin That's good to know :+1:  This one needs rebasing again, though :(
@LK4D4 I think we should try to get this one in soon, too.

**Comment by avagin** [comment]
@LK4D4 I have added two benchmarks. The first one starts a container and the second one starts a second process in CT.
```
# go test -run 'XXX' -bench . -v --tags libct .
PASS
BenchmarkStart	      30	 369049589 ns/op
BenchmarkEnter	     200	   5923668 ns/op
PASS
BenchmarkStart	      20	  96197401 ns/op
BenchmarkEnter	     500	   2462318 ns/op
ok  	_/home/avagin/git/api/libcontainer/integration	17.830s
```

And libct adds only 600kb to a binary file.
```
# export CGO_LDFLAGS="-l:libct.a -l:libnl-route-3.a -l:libnl-3.a -l:libapparmor.a -l:libselinux.a -lm"
# go build -tags libct -o nsinit .
# ls -l nsinit 
-rwxr-xr-x 1 root root 7007088 Apr  1 16:47 nsinit

# export CGO_LDFLAGS="-l:libct.a -lnl-route-3 -lnl-3 -l:libapparmor.a -l:libselinux.a -lm"
# go build -tags libct -o nsinit .
# ls -l nsinit 
-rwxr-xr-x 1 root root 6821224 Apr  1 16:50 nsinit

# go build -o nsinit .
# ls -l nsinit 
-rwxr-xr-x 1 root root 6414600 Apr  1 16:48 nsinit
```

**Comment by avagin** [comment]
@crosbymichael @LK4D4 @vmarmol @mrunalp Can we resume a discussion about this request? Can we declare criterias to include the libct driver into libcontainer?

**Comment by LK4D4** [comment]
I'm personally ready to include it right now as long as it passes the tests. We can test it against docker then to find lacks of functionality and bugs.
I'm still concerned about gap docker -> libcontainer -> libct, what's our idea about updating changes to libct? Now we updating libcontainer pretty often, so, will we update libct in libcontainer, then libcontainer in docker every time?

**Comment by mrunalp** [comment]
I think having the tests working is a good criteria. I will give this one more try today and give me thumbs up.

**Comment by avagin** [comment]
It passes all tests.
https://asciinema.org/a/19728
https://gist.github.com/avagin/7336ccb5e1026e27168e

**Comment by avagin** [comment]
@LK4D4 @mrunalp What do you think about this? libct passes all tests.

Now there is one important flaw. factory.Load() isn't implemented yet. I will implement it in the near future.

@LK4D4 As to your question about updating libct and libcontainer, I've heard about the idea to merge libct into libcontainer.
http://blog.odin.com/serviceprovider/2014/6/10/libcontainer-the-future-facilitator-for-containerized-applications#.VVtT-yc4bK4=

**Comment by mrunalp** [comment]
@avagin 
I tried your branch and see these errors while trying to run the tests. I followed the steps that you have in your video.

```
Makefile:41: warning: ignoring old recipe for target 'integration'
make -C integration
make[1]: Entering directory '/root/gosrc/src/github.com/docker/libcontainer/integration'
go test -bench . -v --tags libct .
=== RUN TestExecPS
--- FAIL: TestExecPS (0.00s)
        exec_test.go:45: <nil>: [7] Invalid configuration:  is not an absolute path or is a symlink
=== RUN TestUsernsExecPS
--- FAIL: TestUsernsExecPS (0.00s)
        exec_test.go:45: <nil>: [7] Invalid configuration:  is not an absolute path or is a symlink
=== RUN TestIPCPrivate
--- FAIL: TestIPCPrivate (0.00s)
        utils_test.go:48: exec_test.go:75: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestIPCHost
--- FAIL: TestIPCHost (0.00s)
        utils_test.go:48: exec_test.go:101: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestIPCJoinPath
--- FAIL: TestIPCJoinPath (0.00s)
        utils_test.go:48: exec_test.go:128: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestIPCBadPath
--- PASS: TestIPCBadPath (0.00s)
=== RUN TestRlimit
--- FAIL: TestRlimit (0.00s)
        utils_test.go:48: exec_test.go:168: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestEnter
--- FAIL: TestEnter (0.00s)
        utils_test.go:48: exec_test.go:289: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestProcessEnv
--- FAIL: TestProcessEnv (0.00s)
        utils_test.go:48: exec_test.go:376: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestProcessCaps
--- FAIL: TestProcessCaps (0.00s)
        utils_test.go:48: exec_test.go:425: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestFreeze
--- FAIL: TestFreeze (0.00s)
        utils_test.go:48: exec_test.go:509: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink

=== RUN TestSystemdFreeze
--- FAIL: TestSystemdFreeze (0.00s)
        utils_test.go:48: exec_test.go:509: unexpected error: [7] Invalid configuration:  is not an absolute path or is a symlink
.....
.....
```

**Comment by avagin** [comment]
@mrunalp This error is reported from ConfigValidator().
```
        if config.Rootfs != cleaned {
                return fmt.Errorf("%s is not an absolute path or is a symlink", config.Rootfs)
        }
```

I think config.Rootfs is empty. I can't reproduce this issue.

**Comment by avagin** [comment]
factory.Load() was implemented.

**Comment by mrunalp** [comment]
I was able to run the tests with libct successfully on Fedora 21. @LK4D4 @crosbymichael could you also give it a try?

**Pull request closed without merging**
