### PR TITLE
gofmt to fix formatting

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM.

I think we should add gofmt to the list of things to check for on CI.

**Comment by mrunalp** [comment]
LGTM

**Comment by LK4D4** [comment]
@dqminh It is already there https://jenkins.dockerproject.org/job/Libcontainer-PRs/683/console:
```
Congratulations!  All Go source files are properly formatted.
```
But seems like not strict enough or I don't know.

**Comment by mrunalp** [comment]
Yeah, not sure why this wasn't caught. It should have been by what we have.

**Comment by rjnagal** [comment]
I think the CI script only checks format on changed files. It would not do anything for existing code.

**Pull request merged**
