### PR TITLE
Add support for kmem limit

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by Mashimiao** [comment]
eh... I'm a little late. #592
So. I will delete my kernel limit code...

**Comment by vmarmol** [comment]
@Mashimiao yes please keep the stats part :) I've been meaning to add that.

**Comment by vmarmol** [comment]
LGTM

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
