### PR TITLE
cgroups: add support for blkio.weight_device

### PR DESCRIPTION
**Pull request by hqhq**
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by hqhq** [comment]
Hi,

Please note that this PR is not ready for merge, systemd part is not working right now, hope I can get some help here. (Sorry if this is not the recommended way, but google group is really not active :( )

I tested this on RHEL 7, which has systemd 208, from what I know, `BlockIODeviceWeight` is already supported from systemd 207, I have confirmed it form systemd's code log, and also we can see it from: http://man7.org/linux/man-pages/man5/systemd.cgroup.5.html

Fs part is working well (I added some necessary code in docker side for test), but if I use systemd, it keeps telling:
./docker run -ti --rm -m 300m --blkio-weight=400 --blkio-weight-device="/dev/sda 500" ubuntu:14.04 /bin/bash
FATA[0002] Error response from daemon: Cannot start container 5c4366c010b525db7f485fef8721cb0125cff890b8ab5da59b2c6c1104eae78d: Invalid argument

I think the command should be right, --device="/dev/sda" is not necessary, and I also tried --blkio-weight-device="8:0 500", but according to my understanding of systemd code, the device should be name as "/dev/sda", not "8:0". And of course I have confirmed sda on my host is using cfq,
cat /sys/block/sda/queue/scheduler
noop deadline [cfq]

So for now, I've no idea why this is not working, confusing me for several days, I'm not familiar with systemd or dbus, can anyone see something wrong here, or is this possible to be a systemd bug?

Any help is appreciated, thank in advance!

**Comment by mrunalp** [comment]
Thanks @hqhq. I can look into it tomorrow. I was in fact looking into systemd code for blkio controller today and saw that it expects device path instead of major minor numbers. It converts the device path into major minor number. http://cgit.freedesktop.org/systemd/systemd/tree/src/core/cgroup.c#n352

**Comment by mrunalp** [comment]
I did some debugging. When I try to write to that cgroup directly it fails. However, it works for blkio.throttle.write_bps_device. Using systemctl segfaults for that property but works for BlockIOWriteBandwidhth

```
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]#  systemctl set-property --runtime docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope "BlockIOWriteBandwidth=/dev/mapper/docker-252:3-386434-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f 10M"
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# cat blkio.throttle.write_bps_device 
253:2 10000000
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# echo "253:2 20000000" > blkio.throttle.write_bps_device
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# 
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# cat blkio.throttle.write_bps_device 
253:2 20000000
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# echo "/dev/mapper/docker-252:3-386434-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f 500" > blkio.weight_device 
-bash: echo: write error: Invalid argument
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# echo /dev/mapper/docker-252:3-386434-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f 500 > blkio.weight_device 
-bash: echo: write error: Invalid argument
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# systemctl set-property --runtime docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope "BlockIODeviceWeight=/dev/mapper/docker-252:3-386434-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f 500"
Segmentation fault (core dumped)
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# 
```
Getting late here. I will continue debugging tomorrow.

**Comment by hqhq** [comment]
@mrunalp If you echo to blkio.weight_device, you should use major minor numbers, it should work.
```
[root@localhost docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope]# echo "8:0 500" > blkio.weight_device
[root@localhost docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope]# cat blkio.weight_device
8:0 500
```

**Comment by hqhq** [comment]
And I tried use systemctl directly as well, it works for me:
```
[root@localhost docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope]# systemctl set-property --runtime docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope "BlockIODeviceWeight=/dev/sda 600"
[root@localhost docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope]#
[root@localhost docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope]# systemctl show docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope  | grep Block
DropInPaths=/run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-BlockIOAccounting.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-BlockIOWeight.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-CPUAccounting.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-Description.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-MemoryAccounting.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-MemoryLimit.conf /run/systemd/system/docker-0e8fb784b93e5e6b2c4f9be0037c1075009c1b4a1bea27481d27b022c6b5e712.scope.d/90-Slice.conf
BlockIOAccounting=yes
BlockIOWeight=400
BlockIODeviceWeight=/dev/sda 600
```

**Comment by mrunalp** [comment]
Sorry missed the lines where I had used device numbers. I am on Fedora 21.
What distro are you on?

```
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# echo "253:2 500" > blkio.weight_device 
-bash: echo: write error: Invalid argument
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# echo "253:2 20000000" > blkio.throttle.write_bps_device
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# cat blkio.weight_device 
[root@localhost docker-585cbac66f8f10d7566b5448959b40663fd90c943718957f3956b55d004c142f.scope]# cat blkio.throttle.write_bps_device 
253:2 20000000
```

**Comment by mrunalp** [comment]
I am guessing in your case it is some intermediate library/binding then.

**Comment by hqhq** [comment]
I'm on RHEL 7, is 253:2 on your box using cfq as IO scheduler? Only devices using cfq can be written to blkio.weight_device, and blkio.throttle.write_bps_device don't have this limit.
You can  cat /sys/block/xxx/queue/scheduler to see the scheduler.

**Comment by hqhq** [comment]
Hi, 
I added read/write bps device support, met the same error on systemd:
```
[root@localhost home]# ./docker_bps run -ti --rm -m 300M --blkio-read-bps-device="/dev/sda 50M" --blkio-write-bps-device="/dev/sda 20M" ubuntu:14.04 /bin/bash
FATA[0003] Error response from daemon: Cannot start container 1e554f3f7fff1459c674d966a88563799807806e85f12d6d799416b2b1eec486: Invalid argument
```
Fs part is working well.

**Comment by mrunalp** [comment]
@hqhq you are right. I was using a device which doesn't have cfq support. I think it should be fairly easy to try the write bps support and see if I can reproduce the issue you are seeing.

**Comment by mrunalp** [comment]
Just got back to this. I see no failures but nothing is written for write bps device.  I will debug it further tomorrow.

**Comment by mrunalp** [comment]
@hqhq Should we implement this using fs workaround in systemd?

**Comment by hqhq** [comment]
@mrunalp Yes, I think that'll be the way to move on, I'll update.

**Comment by hqhq** [comment]
Updated.

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@vmarmol @rjnagal ping

**Comment by rjnagal** [comment]
LGTM.

An added niceness would be to  add another check to verify the scheduler being used by the device. It will help in returning a meaningful error.

**Pull request merged**
