### PR TITLE
mount: Take out the base mounts and move them to the config.

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
Test failure is what we are seeing in master builds, too. Investigating.

**Comment by mrunalp** [comment]
Works on 3.19/3.18.5 kernels but fails on 3.18.9 on Fedora 21. The jenkins failures are related to docker master version in use.

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 ping

**Comment by LK4D4** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
