### PR TITLE
Merge remote-tracking branch 'origin/master' into api-rebase

### PR DESCRIPTION
**Pull request by avagin**
Signed-off-by: Andrey Vagin <avagin@openvz.org>

### CODE REVIEW

**Comment by mrunalp** [comment]
Thanks for doing this! I took a quick look and looks fine. I will test it out, too.

**Comment by mrunalp** [comment]
Basic testing worked for me.

**Comment by vmarmol** [comment]
LGTM

Thanks! Beat me to the rebase :)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
