### PR TITLE
Fix path to /dind

### PR DESCRIPTION
**Pull request by avagin**
That script was moved a few days ago
https://github.com/docker/docker/pull/11373

Signed-off-by: Andrew Vagin <avagin@openvz.org>

### CODE REVIEW

**Comment by tianon** [comment]
:+1: LGTM

**Comment by dqminh** [comment]
LGTM

**Comment by tianon** [comment]
Do you think it might be better to switch `master` to an explicit commit reference to help insulate against issues like this in the future?

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@tianon I think it maybe good to just pull the latest. If we hit this again, we can revisit using commit id :)

**Comment by tianon** [comment]
:+1:

**Pull request merged**
