### PR TITLE
Add a validate script

### PR DESCRIPTION
**Pull request by jfrazelle**
For easier validations.

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by jfrazelle** [comment]
can we get this in it will help jenkins ;)

**Comment by vmarmol** [comment]
LGTM

**Comment by jfrazelle** [comment]
thanks \o/

**Comment by vmarmol** [comment]
:D

**Comment by mrunalp** [comment]
Build broken hack/validate.sh: line 8: /go/src/github.com/docker/docker/hack/make/validate-dco: Permission denied :(

**Comment by jfrazelle** [comment]
/me wonders how drone ever worked :( https://github.com/docker/libcontainer/blob/4c43b0f49880840966cb5df13abeeb19aa8e16d7/.drone.yml

**Comment by jfrazelle** [comment]
omg the shame

**Pull request merged**
