### PR TITLE
Fix tests.

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
A different error here -- System error: operation not permitted.
Closing.

**Comment by crosbymichael** [comment]
@mrunalp something is going on here and not running the user namespaces in a container for the tests.   I don't know what is going on right now.

**Comment by jfrazelle** [comment]
:`(

**Comment by jfrazelle** [comment]
lets never upgrade again

**Comment by mrunalp** [comment]
@crosbymichael @jfrazelle It is very confusing. The behavior is varying across kernels and host docker versions. I will keep looking.

**Pull request closed without merging**
