### PR TITLE
cgroups: systemd: attempt to stop test scope, if any

### PR DESCRIPTION
**Pull request by philips**
As reported in #477 the test scope may not be cleaned up between runs.
In order to fix this we must be polite and remove the scope after we
have done our test and attempt to remove an existing scope if it exists.
This way we can guarantee our test will run.

This replaces https://github.com/docker/libcontainer/pull/477

### CODE REVIEW

**Comment by mrunalp** [comment]
@philips build failed on DCO validation.

**Comment by philips** [comment]
@mrunalp Fixed.

**Comment by crosbymichael** [comment]
@mrunalp could you check this one out on your systemd computerz?

**Comment by mrunalp** [comment]
@crosbymichael Sure

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
Testing this now....

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
