### PR TITLE
First attempt at an integration for checkpoint/restore.

### PR DESCRIPTION
**Pull request by boucher**
The test creates a "cat" process, checkpoints that process, then restores the process, making sure at each point that things are in the correct state.

### CODE REVIEW

**Comment by boucher** [comment]
cc @avagin

**Comment by avagin** [comment]
LGTM. Thanks.

**Comment by boucher** [comment]
@crosbymichael Can you take a look?

**Comment by crosbymichael** [comment]
thanks @boucher

**Pull request merged**
