### PR TITLE
Update existing get state test to work with real ns paths.

### PR DESCRIPTION
**Pull request by vishh**
This should help #512 pass.

### CODE REVIEW

**Comment by rjnagal** [comment]
LGTM.

**Comment by LK4D4** [comment]
I don't see how this is helps. `/fs/network` valid path. And if `Path` is specified for Namespace, then it will be returned from `ns.GetPath`. So this change probably masking possible case when we using arbitrary namespace.

**Comment by vishh** [comment]
@LK4D4: If #512 is a valid fix, this test should be valid as well.

**Comment by rjnagal** [comment]
The test is checking for current state, which should be same as the supplied config in real world, right? The container we are querying is already up and init is pointing to the same config.

**Comment by LK4D4** [comment]
@vishh #512 is invalid fix, it replaces namespaces which was passed with `Path` specified.

**Comment by vishh** [comment]
@LK4D4: Why so? The path that was passed in must match the namespaces of the init process right? Why do we want to support passing arbitrary paths instead of the canonical /proc/pid/ns/ paths?

**Comment by LK4D4** [comment]
@vishh It is good thing to have. For example I can create my namespace with iproute2 and pass it to libcontainer and there is no pid, only path.

**Comment by vishh** [comment]
Ah! I am not aware of that use case. Thanks for clarifying @LK4D4. I will close this PR then?

**Comment by LK4D4** [comment]
@vishh Yup.

**Pull request closed without merging**
