### PR TITLE
README example for using checkpoint/restore.

### PR DESCRIPTION
**Pull request by boucher**

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

I tested on the host with criu built from commit aef7ff0

**Comment by avagin** [comment]
LGTM

**Comment by resouer** [comment]
@boucher Is `ciru` feature now part of dockerd? If not, are you going to implement it soon? I'm very interested in this. :santa:

**Comment by boucher** [comment]
You can use this with docker by building my branch: https://github.com/boucher/docker/tree/boucher-cr

**Comment by resouer** [comment]
Thanks. So eventually your branch will be merged into master?

**Comment by boucher** [comment]
Hopefully :)

**Comment by CrystalQian** [comment]
@boucher Hi,
I have known that the docker integrates CRIU to the commands "docker checkpoint" and "docker restore" from https://github.com/boucher/docker/releases/tag/v1.9.0-experimental-cr.1 , but you said that between checkpoint and restore the process actually stopped for a while, is this a real live migration?

**Pull request merged**
