### PR TITLE
cgroups: add support for oom control

### PR DESCRIPTION
**Pull request by HuKeping**
Redo #412 
This patch add support for diable OOM Killer.

Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by LK4D4** [comment]
@HuKeping I'm not sure but should be pretty easy to write test for this. At least in docker we have test for oom :)

**Comment by HuKeping** [comment]
ok, test will come soon

**Comment by HuKeping** [comment]
hi @LK4D4  I am not quite sure what you would like this test to do.  I think the oom control test would be better in docker/docker?

**Comment by HuKeping** [comment]
do we have plan how often will docker/docker merge libcontainer? it seems a lot of docker's PR depend on libcontainer

**Comment by LK4D4** [comment]
@HuKeping I'm working on move docker to new libcontainer API. There are some problems :) After that we can update libcontainer as often as we need it in docker.

**Comment by HuKeping** [comment]
@LK4D4 OK and by the way what do you want for this PR's test? I didn't see much to do.

**Comment by LK4D4** [comment]
@HuKeping Actually I prefer to have good coverage for libcontainer too. There was pretty bad problems because of tests lack. But if you don't want write a test, then we can leave it for docker birthday party :)

**Comment by HuKeping** [comment]
@LK4D4 yes, of cause I'd like to post a test for this , just  don't know what should it be like. Is it to check the writeable of file memory.oom_control?

**Comment by HuKeping** [comment]
test added, ping @LK4D4

**Comment by LK4D4** [comment]
LGTM

**Comment by vmarmol** [comment]
LGTM

**Comment by HuKeping** [comment]
hi @LK4D4 , would you please help me to review the related PR on docker/docker 
https://github.com/docker/docker/pull/11034

**Pull request merged**
