### PR TITLE
Allow dumped image to be transferred to a criu page server

### PR DESCRIPTION
**Pull request by huikang**
--page-server to specify the IP address of criu page server
  --port to specify the port of the criu page server

Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>

### CODE REVIEW

**Comment by boucher** [comment]
Would be nice to combine this with #543

**Comment by crosbymichael** [comment]
Yes, I would vote for having a struct as input instead of many parameters

**Comment by huikang** [comment]
Me too.
I like the idea of using criuOpts *CriuOpts as the parameter for checkpoint
and restore.

- Hui

**Comment by huikang** [comment]
Hi, Michael,
Maybe you could merge #543 and then I will re-submit a patch for
page-server and port.

- Hui

**Pull request closed without merging**
