### PR TITLE
Check for cmd.Process not-nilness in setnsProcess.terminate()

### PR DESCRIPTION
**Pull request by LK4D4**
We already doing this in initProcess

This will be fix for docker/docker#12627

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by sinchb** [comment]
@mrunalp  @LK4D4  I have the same problem about docker/docker#12627 . And I find that docker 1.6.1 has released today. But I cannot find this commit in the latest docker release. Do I miss something? Or this commit hasn't  been merged into the  latest 1.6.1?

**Comment by LK4D4** [comment]
@sinchb probably not.

**Comment by sinchb** [comment]
@LK4D4 When will this commit be merged into the latest docker release? I think this is a fatal error that will make the docker deamon crash.

**Comment by LK4D4** [comment]
@sinchb Maybe in 1.6.2 next week. Thank you for reminding about this bug.

**Pull request merged**
