### PR TITLE
Change process.Env type to map[string]string

### PR DESCRIPTION
**Pull request by LK4D4**

### CODE REVIEW

**Comment by LK4D4** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html for reference
We're not sure that we want this.

**Comment by dqminh** [comment]
> http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html for reference
We're not sure that we want this.

I think this probably works correcrly. What's your concern ?

**Comment by mrunalp** [comment]
@dqminh Yes, it is correct per the standard, but the concern is that there might be legacy applications that may for some reason depend on the order.

**Comment by LK4D4** [comment]
I'm closing this because actually we don't need write that code by our own.

**Pull request closed without merging**
